name: dmicrokanren
version: 0.5.0
description: The microkanren language implemented with dart
author: hknkoktay <hknkoktay+pub@gmail.com>
homepage: "https://github.com/hkoktay/dmicrokanren"
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
   test: ^1.4.0